# Generated by Django 5.2.13 on 2026-04-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('speed', models.FloatField(default=0)),
                ('density', models.FloatField(default=0)),
                ('bx', models.FloatField(default=0)),
                ('by', models.FloatField(default=0)),
                ('bz', models.FloatField(default=0)),
                ('bt', models.FloatField(default=0)),
                ('kp_index', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
