# Generated by Django 5.2.13 on 2026-04-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_spaceweatheralert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spaceweatheralert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='spaceweatheralert',
            name='flare_class',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='spaceweatheralert',
            name='severity',
            field=models.CharField(default='low', max_length=10),
        ),
    ]
