# Generated by Django 5.2.13 on 2026-04-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_spaceweatheralert_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceweather',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='spaceweatheralert',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
