# Generated by Django 5.2.13 on 2026-04-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_spaceweather_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceweatheralert',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='spaceweatheralert',
            unique_together={('timestamp', 'message')},
        ),
    ]
