# Generated by Django 5.2.13 on 2026-05-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_spaceweatheralert_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceweather',
            name='timestamp',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
    ]
