"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f*=qfhvou45sk!t0_+lgm=av438k12d^qa)c4%&-tjv$d3t56b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"


ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


JAZZMIN_SETTINGS = {
    "site_title": "CosmoPredict Admin",
    "site_header": "CosmoPredict AI",
    "site_brand": "CosmoPredict",
    "site_logo": None,

    "welcome_sign": "Welcome to CosmoPredict Control Center",
    "copyright": "CosmoPredict AI",

    # 🔥 TOP MENU
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"name": "Home", "url": "/", "new_window": True},
        {"name": "API", "url": "/api/", "new_window": True},
    ],

    # 🔥 USER MENU
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/dfordivyansh", "new_window": True},
    ],

    # 🔥 SIDE MENU
    "show_sidebar": True,
    "navigation_expanded": True,

    "order_with_respect_to": ["auth", "api"],

    # 🔥 ICONS
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-astronaut",
        "auth.Group": "fas fa-users",

        "api": "fas fa-satellite",
        "api.spacedata": "fas fa-globe",
    },

    # 🔥 UI TWEAKS
    "changeform_format": "horizontal_tabs",
    "show_ui_builder": False,
}


JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",  # 🌙 DARK MODE

    "dark_mode_theme": "darkly",

    "navbar": "navbar-dark bg-gradient-primary",
    "sidebar": "sidebar-dark-primary",

    "brand_colour": "navbar-primary",

    "accent": "accent-info",

    "navbar_small_text": False,
    "footer_small_text": True,

    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,

    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,

    "button_classes": {
        "primary": "btn-info",
        "secondary": "btn-secondary",
        "info": "btn-cyan",
    }
}

STATICFILES_DIRS = [BASE_DIR / "static"]

JAZZMIN_SETTINGS["site_logo"] = "logo.png"

ASGI_APPLICATION = "config.asgi.application"